# GENERATED by scripts/cbpp-apply from cbpp.conf - do not edit by hand.
#
# Show the banner on interactive login shells only. Without the guards this
# would also fire for scp, rsync-over-ssh and other non-interactive sessions,
# whose protocols break the moment anything unexpected lands on stdout.

if command -v fastfetch >/dev/null 2>&1 && [ -t 1 ] && [ "${TERM:-dumb}" != "dumb" ]; then
	case $- in
	*i*) fastfetch ;;
	esac
fi
